name: spasipokushat
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6

  # Srate management
  get: ^4.6.6

  # Cloud backend service
  appwrite: ^11.0.1
  dart_appwrite: ^11.0.2

  # Analytics
  # appmetrica_plugin: ^1.4.0

  # Utils
  skeletonizer: ^0.8.0
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  permission_handler: ^11.1.0
  pinput: ^4.0.0

  # Map service
  yandex_mapkit: ^3.3.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  geolocator: ^10.1.0
  yandex_geocoder:
    git:
      url: https://github.com/MadBrains/Yandex-Geocoder-Flutter.git
  sliding_up_panel: ^2.0.0+1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.7.0
  pin_code_fields: ^8.0.1
  equatable: ^2.0.5
  get_storage: ^2.1.1
  yookassa_payments_flutter: ^1.3.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon/app_logo.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app-icon/app_logo_foreground.png"
  remove_alpha_ios: true

 

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/onboarding.png
    - assets/app-icon/
